# Generated by Django 3.0.8 on 2020-08-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200803_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='imgUrl',
            field=models.URLField(null=True),
        ),
    ]
