# Generated by Django 3.0.8 on 2020-08-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200803_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='startingBid',
            new_name='currentBid',
        ),
    ]
