# Generated by Django 3.0.8 on 2020-08-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='idNumber',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
