# Generated by Django 3.0.8 on 2020-08-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist_idnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='winner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
